development:
    dialect: postgres
    datasource: host=localhost port=5432 user=postgres password=qwe123jkl dbname=dev_dog sslmode=disable TimeZone=Asia/Shanghai
    dir: migrations

production:
    dialect: postgres
    datasource: host=localhost port=5432 user=postgres password=qwe123jkl dbname=dev_fish sslmode=disable TimeZone=Asia/Shanghai
    dir: migrations